# config 서버는 보통 9000번 사용
server:
  port: 9000

# config server (config 저장소 연결)
spring:
  cloud:
    config:
      server:
        git:
          # 레포지토리 주소
          uri: git@github.com:bu119/MSA-config.git
          # 로컬 SSH 설정을 무시하고 Git 저장소에 대한 연결을 시도
          ignoreLocalSshSettings: true
          # 접근할 수 있게 비밀키 등록
          private-key: |
            -----BEGIN RSA PRIVATE KEY-----
            /////////////// 비밀키  입력 ///////////////
            -----END RSA PRIVATE KEY-----