server:
  port: 8000
#
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: user
#          predicates:
#            - Path=/user/**
#          uri: http://localhost:8081
#        - id: community
#          predicates:
#            - Path=/community/**
#          uri: http://locahost:8082